name: example
description: An example project that demonstrates how to use the ShowHideFAB package.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  show_hide_fab:
    path: ../


flutter:

  uses-material-design: true

