name: show_hide_fab
description: A flutter package that provides wraps around a FloatingActionButton (FAB) in a scaffold to provide easy show/hide functionality.
version: 0.1.0
homepage: https://github.com/Akora-IngDKB/show_hide_fab.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
